// This file was generated by counterfeiter
package namerfakes

import (
	"sync"

	"github.com/ljfranklin/terraform-resource/namer"
)

type FakeNamer struct {
	RandomNameStub        func() string
	randomNameMutex       sync.RWMutex
	randomNameArgsForCall []struct{}
	randomNameReturns     struct {
		result1 string
	}
}

func (fake *FakeNamer) RandomName() string {
	fake.randomNameMutex.Lock()
	fake.randomNameArgsForCall = append(fake.randomNameArgsForCall, struct{}{})
	fake.randomNameMutex.Unlock()
	if fake.RandomNameStub != nil {
		return fake.RandomNameStub()
	} else {
		return fake.randomNameReturns.result1
	}
}

func (fake *FakeNamer) RandomNameCallCount() int {
	fake.randomNameMutex.RLock()
	defer fake.randomNameMutex.RUnlock()
	return len(fake.randomNameArgsForCall)
}

func (fake *FakeNamer) RandomNameReturns(result1 string) {
	fake.RandomNameStub = nil
	fake.randomNameReturns = struct {
		result1 string
	}{result1}
}

var _ namer.Namer = new(FakeNamer)
