#!/bin/bash

set -eu -o pipefail

release_dir="$( cd "$( dirname "$0" )" && cd ../.. && pwd )"
workspace_dir="$( cd "${release_dir}" && cd .. && pwd )"

# env
: ${DOCKERFILE_DIR:?}
: ${TARGETARCH:=amd64}

terraform_version="$( cat "${release_dir}/config/terraform-version" )"

# outputs
if [ "$#" -eq 1 ]; then
  output_dir="$1"
else
  output_dir="${workspace_dir}/build-artifacts"
fi
mkdir -p "${output_dir}/terraform"

tmp_dir="$(mktemp -d /tmp/build-artifacts-XXXXXX)"
trap "{ rm -rf "${tmp_dir}" ; }" EXIT

pushd "${tmp_dir}" > /dev/null
  echo "Downloading artifacts..."
  wget -O terraform_${terraform_version}_linux_${TARGETARCH}.zip https://releases.hashicorp.com/terraform/${terraform_version}/terraform_${terraform_version}_linux_${TARGETARCH}.zip
  wget -O terraform_SHA256SUMS https://releases.hashicorp.com/terraform/${terraform_version}/terraform_${terraform_version}_SHA256SUMS
  wget -O terraform_SHA256SUMS.sig https://releases.hashicorp.com/terraform/${terraform_version}/terraform_${terraform_version}_SHA256SUMS.sig

  echo "Verifying artifacts..."
  # verify checksum file with Hashicorp public key
  # https://www.hashicorp.com/security.html
  gpg --keyserver hkp://keyserver.ubuntu.com --recv-keys 72D7468F
  gpg --verify terraform_SHA256SUMS.sig terraform_SHA256SUMS
  grep terraform_${terraform_version}_linux_${TARGETARCH}.zip terraform_SHA256SUMS | sha256sum -c -

  unzip terraform_${terraform_version}_linux_${TARGETARCH}.zip -d "${output_dir}/terraform"
popd > /dev/null

echo "Building resource..."
pushd "${release_dir}" > /dev/null
  GOARCH="${TARGETARCH}" ./scripts/build "${output_dir}"
popd > /dev/null

cp "${workspace_dir}/${DOCKERFILE_DIR}/Dockerfile" "${output_dir}/"

echo "Successfully fetched all Terraform artifacts!"
