---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: ljfranklin/terraform-resource
    tag: dev

inputs:
- name: resource-src
- name: terraform-src

outputs:
- name: build-artifacts

run:
  path: resource-src/ci/tasks/build-custom-multiarch-artifacts
