#!/bin/bash

set -eu -o pipefail

release_dir="$( cd "$( dirname "$0" )" && cd ../.. && pwd )"
workspace_dir="$( cd "${release_dir}" && cd .. && pwd )"

# env
: ${DOCKERFILE_DIR:?}

# outputs
output_dir="${workspace_dir}/build-artifacts"

TARGETARCH="amd64" "${release_dir}/ci/tasks/build-artifacts" "${output_dir}/amd64"
TARGETARCH="arm64" "${release_dir}/ci/tasks/build-artifacts" "${output_dir}/arm64"
cp "${workspace_dir}/${DOCKERFILE_DIR}/Dockerfile" "${output_dir}/"
