#!/bin/bash

set -eux -o pipefail

docker_dir="$( cd "$( dirname "$0" )" && pwd )"

image_name=ljfranklin/terraform-resource-ci
docker build -t "${image_name}" "${docker_dir}"
docker push "${image_name}"
