#!/bin/bash

set -eux -o pipefail

: ${IMAGE_NAME:=ljfranklin/terraform-resource-ci}

docker_dir="$( cd "$( dirname "$0" )" && pwd )"

docker build -t "${IMAGE_NAME}" "${docker_dir}"
docker push "${IMAGE_NAME}"
