#!/bin/bash

set -eux -o pipefail

docker_dir="$( cd "$( dirname "$0" )" && pwd )"
release_dir="$( cd "${docker_dir}" && cd .. && pwd )"
workspace_dir="$( cd "${release_dir}" && cd .. && pwd )"

source "${release_dir}/.envrc"

terraform_version="$( cat "${release_dir}/config/terraform-version" )"

# outputs
output_dir="${workspace_dir}/build-artifacts"

mkdir -p "${output_dir}/terraform"
wget -O /tmp/terraform.zip https://releases.hashicorp.com/terraform/${terraform_version}/terraform_${terraform_version}_linux_amd64.zip
unzip /tmp/terraform.zip -d "${output_dir}/terraform"
rm /tmp/terraform.zip

pushd "${release_dir}" > /dev/null
  ./scripts/build "${output_dir}"
popd > /dev/null

cp "${docker_dir}/Dockerfile" "${output_dir}/"
