#!/bin/bash

set -eu -o pipefail

release_dir="$( cd "$( dirname "$0" )" && cd .. && pwd )"

if [ "$#" -eq 1 ]; then
  output_dir="$1"
else
  output_dir="${release_dir}/out"
fi
mkdir -p "${output_dir}"

echo "Building resource..."
pushd "${release_dir}/src/terraform-resource" > /dev/null
  go build -o "${output_dir}/check" cmd/check/main.go
  go build -o "${output_dir}/in" cmd/in/main.go
  go build -o "${output_dir}/out" cmd/out/main.go
  echo "Success! Binaries are in '${output_dir}'."
popd > /dev/null
