#!/bin/bash

set -eu -o pipefail

release_dir="$( cd "$( dirname "$0" )" && cd .. && pwd )"

if [ "$#" -eq 1 ]; then
  output_dir="$1"
else
  output_dir="${release_dir}/out"
fi
mkdir -p "${output_dir}"

source "${release_dir}/.envrc"

echo "Building resource..."
go build -o "${output_dir}/check" terraform-resource/cmd/check
go build -o "${output_dir}/in" terraform-resource/cmd/in
go build -o "${output_dir}/out" terraform-resource/cmd/out
echo "Success! Binaries are in '${output_dir}'."
