shared:
  - &failure-alert
    put: slack-alert
    params:
      silent: true
      icon_emoji: ":interrobang:"
      text: |
        *The <$ATC_EXTERNAL_URL/teams/main/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|$BUILD_PIPELINE_NAME - $BUILD_JOB_NAME> job failed!*
  - &success-alert
    put: slack-alert
    params:
      silent: true
      icon_emoji: ":rocket:"
      text: |
        *The <$ATC_EXTERNAL_URL/teams/main/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|$BUILD_PIPELINE_NAME - $BUILD_JOB_NAME> job passed!*

jobs:
  - name: push-prod-image
    on_success: *success-alert
    on_failure: *failure-alert
    plan:
      - in_parallel:
          - get: resource-src
            trigger: true
          - get: terragrunt-release
            trigger: true
            params:
              globs:
                - terragrunt_linux_amd64
                - terragrunt_linux_arm64
          - get: opentofu-release
            trigger: true
            params:
              globs:
                - tofu_*_linux_amd64
                - tofu_*_linux_arm64
      - in_parallel:
          - task: write-docker-metadata-files
            config:
              platform: linux
              image_resource:
                type: docker-image
                source:
                  repository: alpine
                  username: ((docker-hub-skyscrapers-creds.username))
                  password: ((docker-hub-skyscrapers-creds.password))
              inputs:
                - name: resource-src
                - name: opentofu-release
                - name: terragrunt-release
              outputs:
                - name: docker-metadata
              run:
                path: /bin/sh
                args:
                  - "-c"
                  - |
                    TF_VERSION="$(cat opentofu-release/tag)"
                    TF_VERSION="${TF_VERSION:1}" # Trim trailing v from tag
                    TG_VERSION="$(cat terragrunt-release/tag)"
                    TG_VERSION="${TG_VERSION:1}" # Trim trailing v from tag
                    SHA="$(cat resource-src/.git/short_ref)"
                    echo "${TF_VERSION} ${TF_VERSION}-${SHA} ${TF_VERSION}-${TG_VERSION} latest" > docker-metadata/tags
                    echo "{\"opentofu_version\": \"${TF_VERSION}\", \"terragrunt_version\": \"${TG_VERSION}\"}" > docker-metadata/labels
          - task: build-artifacts
            file: resource-src/ci/tasks/build-prod-artifacts.yml
      - task: docker-build
        privileged: true
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: concourse/oci-build-task
          inputs:
            - name: build-artifacts
              path: .
          outputs:
            - name: image
          caches:
            - path: cache
          run:
            path: build
      - put: terragrunt-resource-image
        params:
          image: image/image.tar
          additional_tags: docker-metadata/tags
        get_params:
          skip_download: true

resource_types:
  - name: slack-notification
    type: registry-image
    source:
      repository: cfcommunity/slack-notification-resource
      tag: latest

resources:
  - name: resource-src
    type: git
    icon: github
    source:
      uri: git@github.com:skyscrapers/terragrunt-resource.git
      branch: master
      private_key: ((git-private-key))
  - name: terragrunt-release
    type: github-release
    icon: github
    check_every: 24h
    source:
      owner: gruntwork-io
      repository: terragrunt
      access_token: ((github-repo-access-token-sky-tech))
  - name: opentofu-release
    type: github-release
    check_every: 24h
    icon: github
    source:
      user: opentofu
      repository: opentofu
      access_token: ((github-repo-access-token-sky-tech))
  - name: terragrunt-resource-image
    type: registry-image
    icon: docker
    source:
      repository: skyscrapers/terragrunt-resource
      tag: latest
      username: ((docker-hub-skyscrapers-creds.username))
      password: ((docker-hub-skyscrapers-creds.password))
  - name: slack-alert
    type: slack-notification
    icon: slack
    source:
      url: ((slack-notifications-url))
